package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Shift;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ShiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHIFTS
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    int deleteByPrimaryKey(Integer shiftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHIFTS
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    int insert(Shift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHIFTS
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    Shift selectByPrimaryKey(Integer shiftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHIFTS
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    List<Shift> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHIFTS
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    int updateByPrimaryKey(Shift record);
}