package lt.vu.mybatis.model;

import java.util.Date;

public class Shifts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHIFTS.Shift_id
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    private Integer shiftId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHIFTS.Date
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHIFTS.Shift_id
     *
     * @return the value of PUBLIC.SHIFTS.Shift_id
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    public Integer getShiftId() {
        return shiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHIFTS.Shift_id
     *
     * @param shiftId the value for PUBLIC.SHIFTS.Shift_id
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHIFTS.Date
     *
     * @return the value of PUBLIC.SHIFTS.Date
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHIFTS.Date
     *
     * @param date the value for PUBLIC.SHIFTS.Date
     *
     * @mbg.generated Thu Apr 15 14:10:16 EEST 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }
}